# -*-Makefile-*-

list-available-examples:
  @ls -d */ | tr -d "\/"

clean NAME:
  rm -rf {{NAME}}/{build,install}
  rm -rf {{NAME}}/src/CMakeLists.txt

prepare NAME:
  sed 's/XXX/{{NAME}}/g' meson.build > {{NAME}}/src/meson.build
  cp globber.sh {{NAME}}/src/

install NAME: (prepare NAME)
  meson setup {{NAME}}/build {{NAME}}/src
  meson compile -C {{NAME}}/build
  meson install -C {{NAME}}/build

run NAME *ARGS: (install NAME)
  ./{{NAME}}/install/bin/example-{{NAME}} {{ARGS}} --macro-path {{NAME}}/macs

run-all:
  for example in `just list-available-examples`; do \
    just run $example -n 100; \
  done
