# -*-Makefile-*-

test-all:
  t0=$(just test-fetch-content)
  t1=$(just test-fetch-content-recompile)
  t2=$(just test-subdirectory)
  t3=$(just test-independent-installation)

  [[ t0 && (t1 && (t2 && t3)) ]]


test-fetch-content:
  #!/usr/bin/env bash
  bash test_fetch_content.sh
  if [[ $? -eq 0 ]]; then
    printf "\\033[32m => Client project compiled successfully with fetch content";
  else
    printf "\\033[91m => Client project could not be compiled with fetch content";
  fi

test-fetch-content-recompile:
  #!/usr/bin/env bash
  sudo -E bash test_fetch_content_recompile.sh
  if [[ $? -eq 0 ]]; then
    printf "\\033[32m => Client project recompiled without using the network";
  else
    printf "\\033[91m => Client project could not be recompiled without using the network";
  fi

test-subdirectory:
  #!/usr/bin/env bash
  bash test_subdirectory.sh
  if [[ $? -eq 0 ]]; then
    printf "\\033[32m => Client project compiled successfully with nain4 as a subdirectory";
  else
    printf "\\033[91m => Client project could not be compiled with nain4 as a subdirectory";
  fi

test-independent-installation:
  #!/usr/bin/env bash
  bash test_independent_installation.sh
  if [[ $? -eq 0 ]]; then
    printf "\\033[32m => Client project compiled successfully with an independent installation of nain4";
  else
    printf "\\033[91m => Client project could not be compiled with an independent installation of nain4";
  fi
