# -*-Makefile-*-

test-all:
  #!/usr/bin/env sh
  just test-fetch-content           ;(( status |= $? ))
  just test-fetch-content-recompile ;(( status |= $? ))
  just test-subdirectory            ;(( status |= $? ))
  just test-independent-installation;(( status |= $? ))

  exit $status


test-fetch-content:
  #!/usr/bin/env bash
  bash test_fetch_content.sh
  status=$?
  just print $status "using fetch content"
  exit $status

test-fetch-content-recompile:
  #!/usr/bin/env bash
  bash test_fetch_content_recompile.sh
  status=$?
  just print $status "a second time without a network"
  exit $status


test-subdirectory:
  #!/usr/bin/env bash
  bash test_subdirectory.sh
  status=$?
  just print $status "using nain4 as a subdirectory"
  exit $status


test-independent-installation:
  #!/usr/bin/env bash
  bash test_independent_installation.sh
  status=$?
  just print $status "using an independent installation of nain4"
  exit $status


print exit_status explanation:
  #!/usr/bin/env bash
  if [[ {{exit_status}} -eq 0 ]]; then
    printf "\\033[32m => Client project compiled successfully {{explanation}}\x1B[37m\n";
  else
    printf "\\033[91m => Client project could not be compiled {{explanation}}\x1B[37m\n";
  fi
