# -*-Makefile-*-

run: install
    build/try-arrow

example: install
    build/arrow-example

simple-list: install
    build/simple-list

install:
    meson setup build src
    meson compile -C build
    meson install -C build

clean:
    rm build ../install/try-arrow -rf
