# -*-Makefile-*-

test-app:
  just run-app macs/run.mac


compile-app:
  cmake -S . -B build
  cmake --build build


run-app N='': compile-app
  #!/usr/bin/env sh
  ./build/n4app-00-basic {{N}}
  exit $?
