# -*-Makefile-*-

test:
  just run --beam-on 10

build:
  cmake -S src -B build/app
  cmake --build build/app

run *ARGS: build
  #!/usr/bin/env sh
  # CHANGEME-my-n4-app: change my-n4-app with a name that better suits your
  # project. At the same time you must change it in the `src/CMakeLists.txt`.
  ./build/app/my-n4-app {{ARGS}}
  exit $?

clean:
  rm build -rf

view:
  nix run --impure github:guibou/nixGL -- just run
