# -*-Makefile-*-

# Run all tests in hand-written loop: more informative and colourful than ctest
test-all *FLAGS:
	just test '' {{FLAGS}}


# Run a selection of tests
test PATTERN *FLAGS: build-src build-tests
	sh ../install/nain4-tests/bin/run-each-test-in-separate-process.sh {{PATTERN}} {{FLAGS}}

build-src:
	#!/usr/bin/env sh
	cmake -S src -B build/nain4 -DCMAKE_BUILD_TYPE=RelWithDebInfo
	cmake --build build/nain4 --target install -j

build-tests:
	#!/usr/bin/env sh
	cmake -S test -B build/nain4-tests -DCMAKE_BUILD_TYPE=RelWithDebInfo
	cmake --build build/nain4-tests --target install -j

clean:
	rm build -rf
	rm ../install -rf
